name: py36
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _tflow_180_select=1.0=gpu
  - absl-py=0.2.2=py36_0
  - astor=0.6.2=py36_0
  - blas=1.0=mkl
  - bleach=1.5.0=py36_0
  - cairo=1.14.12=h77bcde2_0
  - cudatoolkit=9.0=h13b8566_0
  - cudnn=7.1.2=cuda9.0_0
  - cupti=9.0.176=0
  - cycler=0.10.0=py36_0
  - gast=0.2.0=py36_0
  - glib=2.53.6=h5d9569c_2
  - grpcio=1.12.0=py36hdbcaa40_0
  - gst-plugins-base=1.12.4=h33fb286_0
  - gstreamer=1.12.4=hb53b477_0
  - harfbuzz=1.7.6=hc5b324e_0
  - html5lib=0.9999999=py36_0
  - imageio=2.3.0=py36_0
  - libedit=3.1.20170329=h6b74fdf_2
  - libffi=3.2.1=hd88cf55_4
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-ng=7.2.0=hdf63c60_3
  - libgfortran=3.0.0=1
  - libgfortran-ng=7.2.0=hdf63c60_3
  - libiconv=1.15=h63c8f33_5
  - libopenblas=0.2.20=h9ac9557_7
  - libprotobuf=3.5.2=h6f1eeef_0
  - libstdcxx-ng=7.2.0=hdf63c60_3
  - libxml2=2.9.8=h26e45fe_1
  - markdown=2.6.11=py36_0
  - ncurses=6.1=hf484d3e_0
  - numpy=1.14.3=py36h28100ab_2
  - numpy-base=1.14.3=py36h0ea5e3f_1
  - olefile=0.45.1=py36_0
  - opencv=3.4.1=py36h6fd60c2_1
  - pip=10.0.1=py36_0
  - protobuf=3.5.2=py36hf484d3e_0
  - pyparsing=2.2.0=py36_0
  - python=3.6.5=hc3d631a_2
  - qt=5.6.2=hd25b39d_14
  - readline=7.0=ha6073c6_4
  - setuptools=39.2.0=py36_0
  - six=1.11.0=py36h372c433_1
  - sqlite=3.23.1=he433501_0
  - tensorboard=1.8.0=py36hf484d3e_0
  - tensorflow=1.8.0=hb11d968_0
  - tensorflow-base=1.8.0=py36hc1a7637_0
  - tensorflow-gpu=1.8.0=h7b35bdc_0
  - termcolor=1.1.0=py36_1
  - tk=8.6.7=hc745277_3
  - tornado=5.0.2=py36_0
  - werkzeug=0.14.1=py36_0
  - wheel=0.31.1=py36_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=ha838bed_2
  - bzip2=1.0.6=1
  - ca-certificates=2018.4.16=0
  - dbus=1.13.0=h3a4f0e9_0
  - expat=2.2.5=0
  - ffmpeg=3.2.4=3
  - fontconfig=2.13.0=0
  - freetype=2.8.1=0
  - giflib=5.1.4=0
  - graphite2=1.3.11=0
  - hdf5=1.10.2=0
  - icu=58.2=0
  - jasper=1.900.1=4
  - jpeg=9b=2
  - kiwisolver=1.0.1=py36_1
  - libpng=1.6.34=0
  - libtiff=4.0.9=0
  - libuuid=1.0.3=1
  - libwebp=0.5.2=7
  - libxcb=1.13=0
  - matplotlib=2.2.2=py36_1
  - openblas=0.2.20=8
  - openssl=1.0.2o=0
  - pcre=8.41=1
  - pillow=5.1.0=py36_0
  - pixman=0.34.0=2
  - pyqt=5.6.0=py36_5
  - python-dateutil=2.7.3=py_0
  - pytz=2018.4=py_0
  - sip=4.18=py36_1
  - x264=20131218=0
  - xorg-libxau=1.0.8=3
  - xorg-libxdmcp=1.1.2=3
  - certifi=2018.4.16=py36_0
  - cmake=3.12.0=h307fef2_0
  - libcurl=7.61.0=h1ad7b7a_0
  - libssh2=1.8.0=h9cfc8f7_4
  - rhash=1.3.6=hb7f436b_0
  - pip:
    - cloudpickle==0.5.3
    - cython==0.28.3
    - dask==0.17.5
    - datetime==4.2
    - decorator==4.3.0
    - easydict==1.7
    - h5py==2.9.0
    - msgpack==0.5.6
    - msgpack-numpy==0.4.3
    - munkres==1.0.12
    - networkx==2.1
    - opencv-python==3.4.1.15
    - pyarrow==0.9.0
    - pycocotools==2.0
    - pyqt5==5.12.1
    - pyqt5-sip==4.19.15
    - pywavelets==0.5.2
    - pyyaml==3.12
    - pyzmq==17.0.0
    - scikit-image==0.14.0
    - scipy==1.1.0
    - setproctitle==1.1.10
    - shapely==1.6.4.post1
    - tabulate==0.8.2
    - toolz==0.9.0
    - torch==1.0.1.post2
    - torchlight==1.0
    - torchvision==0.2.2.post3
    - tqdm==4.23.4
    - zope.interface==4.5.0
prefix: /root/anaconda2/envs/py36

